// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMwOhdj6kavIFcl-pmv-9rFrJ0g5zI_3I',
    appId: '1:660030312034:web:a93ea95d532bbf320a8b3b',
    messagingSenderId: '660030312034',
    projectId: 'talkway-app',
    authDomain: 'talkway-app.firebaseapp.com',
    storageBucket: 'talkway-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTCDyVt0pgFJvDrGHNr0pnrpSr7wCpnUA',
    appId: '1:660030312034:android:a543876117038bf50a8b3b',
    messagingSenderId: '660030312034',
    projectId: 'talkway-app',
    storageBucket: 'talkway-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFRT-KYUkU0MhPEFfnbjonCrdMnhtH7KE',
    appId: '1:660030312034:ios:5a2a00898f6298ad0a8b3b',
    messagingSenderId: '660030312034',
    projectId: 'talkway-app',
    storageBucket: 'talkway-app.firebasestorage.app',
    iosBundleId: 'com.example.talkway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFRT-KYUkU0MhPEFfnbjonCrdMnhtH7KE',
    appId: '1:660030312034:ios:5a2a00898f6298ad0a8b3b',
    messagingSenderId: '660030312034',
    projectId: 'talkway-app',
    storageBucket: 'talkway-app.firebasestorage.app',
    iosBundleId: 'com.example.talkway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMwOhdj6kavIFcl-pmv-9rFrJ0g5zI_3I',
    appId: '1:660030312034:web:6f36a2d8483c85560a8b3b',
    messagingSenderId: '660030312034',
    projectId: 'talkway-app',
    authDomain: 'talkway-app.firebaseapp.com',
    storageBucket: 'talkway-app.firebasestorage.app',
  );
}
